### ISSUE TITLE
Async custom codegen functions?

### ISSUE THREAD

**Issue by tannerntannern** [mmkal/ts#140]
First off -- I love the `eslint-plugin-codegen` tool!  The idea of having code generation handled by the linter is really smart.

Is there any chance that you could allow custom codegen functions to be async?  Let me know if there's anything I can help with!

**Comment by mmkal** [comment]
I've thought about it, but haven't head a use-case yet which has needed async functions. But it's on the wishlist - I'd love to be able to get similar functionality to [F# type providers](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/type-providers/). I'd be interested to find out if it's possible. I'm not aware of a way to tell eslint to wait for a promise to resolve, or give it a callback before reporting errors/applying fixes. An extreme solution would be to shell out to a separate process with `child_process.execSync`.

Do you have a particular use case in mind?

**Comment by tannerntannern** [comment]
I actually had to resort to `child_process.execSync` in my case, haha.  I was using [widdershins](https://github.com/Mermade/widdershins) to generate API documentation markdown from an OpenAPI spec to stick in my README, and widdershins has no sync API.  Luckily they do have a CLI, so I was able to use that with `execSync` to get unblocked, but it still wasn't ideal.

**Comment by tannerntannern** [comment]
Another potential use-case is generating TypeScript interfaces from JSON schemas using [json-schema-to-typescript](https://www.npmjs.com/package/json-schema-to-typescript), which has no synchronous API.

**Comment by tannerntannern** [comment]
I ended up creating a little npm package to deal with this problem in general, [node-force-sync](https://www.npmjs.com/package/node-force-sync).  There are a few other packages that can force synchronous execution, but they are more complicated than they need to be IMO.  Just mentioning here in case someone else finds it useful.
