### ISSUE TITLE
fs-syncer remove()

### ISSUE THREAD

**Issue by elmpp** [mmkal/ts#217]
Hey. Just a thought for fs-syncer - could it add `removeWrite`/`removeSync` methods to clear down files/dir and be useful for jest.afterAll() or similar?

**Comment by mmkal** [comment]
Do you mean you want to delete all files? Would `fsSyncer(based it, {}).sync()` work if so?

**Comment by elmpp** [comment]
yeah i suppose it, would thinking about it.

**Comment by elmpp** [comment]
yeah of course. Thanks for this neat little util
