### ISSUE TITLE
Bug with `.toEqualTypeOf`

### ISSUE THREAD

**Issue by papb** [mmkal/ts#225]
The following does not give an error (`expect-type@0.11.0`):

```ts
expectTypeOf<
	{ a: boolean }
>().toEqualTypeOf<
	{ a: boolean | undefined }
>();
```

**Comment by papb** [comment]
By the way, if you want you can just use [my `StrictEqual` implementation](https://github.com/papb/assorted-ts-utils):

```ts
import { StrictEqual } from '@papb/assorted-ts-utils';
```

**Comment by mmkal** [comment]
Do you have `strictNullChecks` turned off? Your code is erroring as expected for me, [same in typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwKYA8xIMYwCoE90DyAZgL5xFQQhwDkq6WAtDPkjQFDv2Y6vEA8COAEMAXHABGECABskwgHZwSAPgAUASgB0MCAFEAjgFdhMvISKCR4qbPlKAPnCMKAJkiLAFSV8vUaAbiA).

**Comment by papb** [comment]
Hmmm, that's odd, I had `"strict": true` in my tsconfig since the beginning, but now I can't reproduce it anymore. I must have made some other mistake. Thanks!!
