### ISSUE TITLE
Remove Ass/Donkey from animal dictonary

### ISSUE THREAD

**Issue by jdarrohn** [mmkal/ts#229]
Love the package, but caught this, and while I laughed at `bubbly ass donkey`, I wouldn't want to take it to production. Would you consider removing it?

**Comment by mmkal** [comment]
@jdarrohn I think there are potentially many offensive combinations of adjectives/animals - but there's another donkey entry in there too so in this case it doesn't make sense to keep in. Removing in the linked PR.

**Comment by mmkal** [comment]
Fixed in v0.4.0: https://www.npmjs.com/package/memorable-moniker/v/0.4.0

**Comment by martaver** [comment]
This literally the best thing I've read on GitHub all year.
