### ISSUE TITLE
Using pure javascript instead of node dependencies

### ISSUE THREAD

**Issue by omertoast** [mmkal/ts#249]
I'm developing a product on Cloudflare Workers and I wanted to use io-ts-extra for handling optional types. Unfortunately, workers platform does not support Node, so It's not possible to use the library in workers environments. I wonder if it's possible to shift node dependencies to javascript API for the library's more useability?

**Comment by mmkal** [comment]
I thought I replied to this a few weeks ago, not sure where it went. Isn’t webpack a good option for this use case?

**Comment by omertoast** [comment]
Cloudflare does not recommend using webpack for the new modules version of the workers. Even if so, I don't think the webpack is capable of transforming complex libraries like `fs`.

**Comment by mmkal** [comment]
`fs` isn’t used so should be fine. Admittedly I haven’t use CF workers but webpack can just bundle the same code that you plan on running. I can’t see what the issue would be.

**Comment by omertoast** [comment]
You might be right but even if webpack polyfills all of the libraries without an issue, using webpack is such a headache by itself. `io-ts-types` worked without a problem so I went with that.

**Comment by mmkal** [comment]
Ok. It’s worth noting that io-ts-extra doesn’t have _any_ node dependencies beyond `import {EOL} from ‘os’` which any bundler would be able to handle, I would hope! Great that io-ts-types ended up working for you, but if you need to use this or other libraries as your project grows, maybe it’d be worth looking at parcel if you want something with less configuration than webpack, or esbuild if you want something faster.
