### ISSUE TITLE
Is `toEqualTypeOf` as strong as this `IsExact` implementation from conditional-type-checks?

### ISSUE THREAD

**Issue by papb** [mmkal/ts#32]
I found [this implementation of `IsExact` in a package called conditional-type-checks](https://github.com/dsherret/conditional-type-checks/blob/01215056e8b97a28c5b0311b42ed48c70c8723fe/index.ts#L43).

I liked how it works, it *seems* to make more checks than your implementation of `Equal`:

https://github.com/mmkal/ts/blob/241a482e4d4d308548cdef2414c9c4f1ddfce3f6/packages/expect-type/src/index.ts#L17-L24

Question: are these implementations equivalent? Or is one of these implementations stricter than the other?

**Comment by mmkal** [comment]
@papb you are right, they are not! The one in conditional-type-checks accounted for deeply-nested `any`s. See the PR linked above for the fix.

**Comment by mmkal** [comment]
released: https://www.npmjs.com/package/expect-type/v/0.7.4
