### ISSUE TITLE
False positives for type equality

### ISSUE THREAD

**Issue by dfreeman** [mmkal/ts#98]
Unfortunately, while #33 now catches deep `any`s, it seems to have weakened other equality checks. In 0.7.3, this assertion would (correctly) fail:

```ts
type NoParam = () => void;
type HasParam = (s: string) => void;

expectTypeOf<NoParam>().toEqualTypeOf<HasParam>();
```

But starting with 0.7.4, which contains that fix, this assertion passes.

**Comment by mmkal** [comment]
Thanks @dfreeman, good catch. This is a bug - although it's often a good idea to narrow down assertions on functions with `.parameters`, `.returns` etc. e.g.

```typescript
type NoParam = () => void
type HasParam = (s: string) => void

expectTypeOf<NoParam>().parameters.toEqualTypeOf<[]>()
expectTypeOf<NoParam>().returns.toEqualTypeOf<void>()

expectTypeOf<HasParam>().parameters.toEqualTypeOf<[string]>()
expectTypeOf<HasParam>().returns.toEqualTypeOf<void>()
```

This isn't always possible though, so will find a fix for the `toEqualTypeOf` regression.
